<?php

namespace GameBundle\Repository;

/**
 * HousesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HousesRepository extends \Doctrine\ORM\EntityRepository
{
}
