<?php

namespace GameBundle\Repository;

/**
 * Member_of_a_familyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Member_of_a_familyRepository extends \Doctrine\ORM\EntityRepository
{
}
