got_house:
    resource: "@GotBundle/Resources/config/routing/house.yml"
    prefix:   /house

got_homepage:
    path:     /
    defaults: { _controller: GotBundle:Default:index }

got_soldiers:
        resource: "@GotBundle/Resources/config/routing/soldiers.yml"
        prefix:   /soldiers
