GotBundle\Entity\House:
    type: entity
    table: null
    repositoryClass: GotBundle\Repository\HouseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        sigil:
            type: string
            length: 255
            nullable: true
        money:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
