GameBundle\Entity\Member_of_a_family:
    type: entity
    table: null
    repositoryClass: GameBundle\Repository\Member_of_a_familyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: first_name
        healthPoints:
            type: integer
            column: health_points
        strength:
            type: integer

    manyToOne:
            houses:
                targetEntity: Houses
                inversedBy: member_of_a_family
                joinColumn:
                    name: houses_id
                    referencedColumnName: id
                    onDelete: CASCADE
    lifecycleCallbacks: {  }
