GameBundle\Entity\Soldiers:
    type: entity
    table: null
    repositoryClass: GameBundle\Repository\SoldiersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
        cost:
            type: string
            length: 255
        healthPoints:
            type: integer
            column: health_points
        strength:
            type: integer
    lifecycleCallbacks: {  }
