<?php

namespace GotBundle\Repository;

/**
 * FamilyMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
