<?php

namespace GotBundle\Repository;

/**
 * FamilyMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyMemberRepository extends \Doctrine\ORM\EntityRepository
{
    function getFamilyMembersByHouse() {
        $qb = $this->createQueryBuilder('fm'); // on crée un alias "m" qui correspond à la table Hotel
        $qb ->select("fm.firstName")
            ->join("fm.house", "h") // permet de faire une jointure vers la table house en utilisant l'alias de house
            ->groupBy('fm.house');
        return $qb->getQuery()->getResult(); // retourne le résultat de la recherche.
    }
}
