<?php

namespace GotBundle\Repository;

/**
 * SoldiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoldiersRepository extends \Doctrine\ORM\EntityRepository
{
}
