<?php

namespace GotBundle\Repository;

/**
 * SoldierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoldierRepository extends \Doctrine\ORM\EntityRepository
{
}
