house_index:
    path:     /
    defaults: { _controller: "GotBundle:House:index" }
    methods:  GET

house_show:
    path:     /house/{id}
    defaults: { _controller: "GotBundle:House:show" }
    methods:  GET



